### ISSUE TITLE
Bypass login by enabling autologin

### ISSUE THREAD

**Issue by ntquyen** [paulshir/coreos-hyperv#12]
Just a small question: How can I run the command `boot_kernel coreos.autologin` when booting coreos node? I'm using you code to create coreos in my hyper-v but I don't know how to do it.

Thanks!

**Comment by paulshir** [comment]
Hi,

You can add the following at the end of the config when creating the machines.
``` yaml
write_files:
  - path: /usr/share/oem/grub.cfg
    content: |
      set linux_append="coreos.autologin=tty1"
```

See site https://coreos.com/os/docs/latest/other-settings.html for more details. You will have to start up the machines with this config and then reboot them once they have fully started up. If you only want to do it on a once off basis you could try interrupting grub at startup and edit the config then but I'm not familiar with this method.
